wasa2il/core/ajax/document.py, wasa2il/core/urls.py, wasa2il/core/views.py, wasa2il/locale/is/LC_MESSAGES/django.po, wasa2il/templates/core/document_update.html, wasa2il/templates/core/issues_new.html, wasa2il/templates/core/polity_detail.html
1. Ability to change proposals before they're put to a vote
2. An independent page showing all new/open issues in a given polity (handy when there are more than one issue in voting and links need to be pinned on Facebook or something)
Icelandic translations also updated accordingly, each in an independent commit.
Please see individual commits for details in code changes.
=> 2 changes: Modifiable change proposals and a page for new issues

README.md, initial_setup.py
- initial_setup.py:
- Fix locale->wasa2il/locale path change
- Correct instructions when running in virtualenv (python path)
- Deduplicate instruction in README.md, some of it was covered in initial_setup.py
=> Simplify installation instructions, fix initial_setup.py

wasa2il/templates/core/polity_detail.html
This is what I use 99% of the time and when on mobile, I need to scroll endlessly down to see new issues.
Therefore I suggest 'New issues' should be moved to the top for increased user happiness!
=> UI: Move 'new issues' to the top. Closes #47

wasa2il/templates/core/polity_detail.html
1. The Subpolity button did not fit in with the other buttons purpose wise so I removed it.
Now these 3 buttons have one purpose, to jump to each section respectively.
(If we need to access the subpolities, we just click the Pirate logo and go to the front page).
@helgihg mentioned we should create a tree for that and I think we should do that on the front page.
If we do it in a modal (which the removed button did), it will be nasty when the tree grows large.
2. Make memberstatusbox not float right, it broke longer policy names.
3. Instead of the purple nav-pills, use buttons to emphasize their clickability.
===
**Before:**
===
**After:**
=> UI: minor cleanup on polity page

core/static/css/application.css, wasa2il/templates/core/_document_agreement_list_table.html
It was hard to find the statistics, you had to click the document, then the referenced issue.
Now the stats are available at the polity page:
NOTE:
Since I did not have any reliable dummy data, this might now work on some edge cases, who knows?
=> Add voting stats to agreements list on polity page

core/models.py
I was unable to view the Candidates category in the x.piratar.is admin UI, due to Unicode crashes. 
This PR fixes that by updating __unicode__ in the Candidates model, but also updates the other __unicode__ methods to follow the same pattern.
=> Fix unicode display issues which broke the admin UI

wasa2il/templates/profile.html
Minor cleanup on users profile page, picture was huge and out of line with other elements.
Now using bootstrap columns.
**Mobile:**
=> UI: clean up users profile, picture was huge,fixed

core/migrations/0003_auto_20160617_1102.py
Github's mergability checks didn't catch this, as it's django specific.
=> Fix migration conflict

wasa2il/templates/core/polity_detail.html
We were missing a shortcut nav button for elections. 
Now we have the 4 categories:
=> UI: adding shortcut button for elections

core/middleware.py, core/migrations/0007_default_language_code.py, core/models.py, core/views.py, wasa2il/settings.py, wasa2il/templates/base.html
Users could change the setting but it did not have any effect. Now it works and everyone's setting is set to settings.LANGUAGE_CODE which was their only choice before, although their selection might not have matched what was displayed.
=> Enable UI language choice in settings

wasa2il/templates/base.html
I think I broke this a while ago when I removed a container class. Fixing it now by adding the missing class :smile_cat: 
Thx to @PeterTheOne for noticing this on his PR #109 (which can be closed as well)
**Before**:
**After**:
On a related note, it would be nice to add a button or something 'nicer' to click :smile:
=> Fix top menu right margin issue, was close to edge

core/templatetags/wasa2il.py, requirements.txt
WIP since the results are not as good as smartcrop.js, there is a bit of
empty space on the left side while smartcrop.js images are more symmetric. The algorithm might need to be rebased on latest smartcrop.js or parameters adjusted.
=> #121 Make sure generated thumbnails have requested resolution

core/static/css/application.css, wasa2il/locale/is/LC_MESSAGES/django.po, wasa2il/templates/core/_election_candidate_list.html, wasa2il/templates/core/election_detail.html
- Added buttons which move candidates to top and bottom.
- Small jQuery and CSS refactoring
Note: do not merge yet, the freeze/pin button does nothing at the moment.
Also, need to move the candidate number CSS wise.
I am not sure if the arrows are intuitive enough, I was searching for a 'double up/down' arrows but could not find any. However I found them in another library, font awesome. Should we add that as a dependency as well? (I am not a fan of adding to many libraries)
They look like this:
http://fontawesome.io/icon/angle-double-up/
Compare it with the screenshot:
Test if you feel like it and comment!
=> WIP: Add vote buttons which move cand to top, bottom

election/utils.py
We need to be able to run `election/util.py` as a standalone tool for recounts and other post-processing. This PR removes the dependency on Django when run directly.
See https://github.com/piratar/wasa2il/wiki/Elections-and-recounts for an example of the work-flows we're failing to support without this patch. :-)
=> Make election/util.py not depend on Django

election/utils.py
The candidate rank statistics would crash if the ballots had holes in them (which can happen if a candidate withdraws mid-election). This fixes that problem by generating new consecutive rankings for use with the statistics.
=> Fix candidate rank statistics bug

.travis.yml
Tests would fail on PRs from forks as Travis restricts acces to secure ENV variables from PRs from this project only. See: https://blog.travis-ci.com/2016-07-07-security-advisory-encrypted-variables
=> Allow for tests to run from forks as well

wasa2il/default_settings.py
So this website can work:
https://wasa2il-development.herokuapp.com/
This is automatically built whenever a new branch to development is pushed.
=> Add Heroku to ALLOWED_HOSTS for development

README.md
If we are supporting `docker-compose`, lets add **basic** instructions on the frontpage
=> Add basic `docker-compose` instructions to README

docker-compose.yml
Also adds `depends_on: db` so we can _try_ to make the APP container **wait** until the DB container (mysql) is ready. If mysql is not ready in time, django will **fail** to connect.
Other way is to first do
`docker-compose up db`  
wait 2-3 seconds and then do
`docker-compose up wasaweb`
which is not optimal, we prefer to use only one command.
=> Use docker-compose versioning syntax

election/test/test_schulze.py
They should probably be moved in another class later
This test would have caught the issue in #214 when an installed package breaks something
=> Add basic tests for statuscodes 200 and 404

wasa2il/templates/_sidenav_polity.html
Also minor code re-format. Put `a` in its own line
**Before**
**After**
=> Align font awesome icons with the fa-fw class
