piratar/wasa2il

initial_setup.py
requirements.txt
wasa2il/local_settings_sqlite3.py

Creating a setup script and making wasa2il work on windows machines

---

wasa2il/initial_data.json

Add initial data for the database

---

Dockerfile

Makes sense when using Git & Docker for Windows. CC @gakera

Don't rely on shebang as it does not work for files with Windows line endings

---

wasa2il/core/static/css/application.css
wasa2il/templates/base.html

Added a CSS media query which makes the nav dropdown background purple.
Fixes #28

Mobile navbar was transparent, is now purple

---

Dockerfile
docker-compose.yml

Install docker-compose (google it) and run with
`docker-compose build`
`docker-compose up`
Files can be edited on your local machine and are shared with the docker
container.
Our previous Dockerfile did not update our files on the container when edited on local machine. Restarting the container was required.
We could concatinate this to a single Dockerfile but docker-compose allows us to expand, f.x. if we want to containarize the database, f.x. a postgres container.

Adding docker-compose functionality.

---

Dockerfile
docker-compose.yml
requirements.txt
wasa2il/local_settings.py-mysql-docker
wasa2il/templates/base.html
wasa2il/templates/core/polity_detail.html
wasa2il/templates/registration/password_change_done.html

I branched this one out from another branch where I had improved the docker setup.
(This should have been 2 separate PR)
Docker improvements:
Using a separate container for mysql.
Start with `docker-compose up` - more details in docker-compose.yml
UI: fix the left padding added because of multiple css "container" classes. Only one should be used.
See individual comments for more.

UI fix left padding + docker settings

---

wasa2il/core/static/css/application.css

Improves readability, so comments by different users wont merge.
Comment if you think the colors should be made even darker
Closes #52

Make every other comment background darker in color

---

wasa2il/core/static/css/application.css

Truncate long comments by adding a horizontal scrollbar

---

Dockerfile
core/static/css/application.css

Update working directory for docker

---

Dockerfile
core/static/css/application.css

- Added line break after first line (name)
- Italized the date and added more spacing.
- Add border for better visual separation

Improve comments readability in discussions.

---

core/static/css/application.css
wasa2il/templates/core/_election_candidate_list.html
wasa2il/templates/core/election_detail.html

This is still a work in progress, need to tweak the user names. Maybe put them in a separate line.
The voting looks like this currently:

Ui votes updown buttons - WIP, feedback welcome

---

gateway/icepirate.py

Minor bugfixes... again.

---

core/migrations/0001_initial.py
core/models.py

This should allow initial setup to work properly again.

Fix initial migration

---

.gitignore

(The 'venv' folder is not a fixed folder name but recommended in the readme when using a virtualenv)

Ignore sqlite db file and virtualenv folder

---

core/ajax/__init__.py
core/management/commands/load_fake_data.py
core/migrations/0004_auto_20160727_0037.py
core/models.py
core/views.py
wasa2il/templates/core/election_detail.html

See individual commit messages please. :)

Works in progress: Cross-polity election participation rules

---

core/ajax/__init__.py
core/migrations/0005_election_starttime_votes.py
core/models.py
core/static/js/wasa2il.js
wasa2il/locale/is/LC_MESSAGES/django.po
wasa2il/templates/core/election_detail.html

Seems people like to have a gap between accepting candidates and starting to vote. This makes that possible.
Also, updating Icelandic.

Add explicit start-time for elections

---

wasa2il/locale/is/LC_MESSAGES/django.po
wasa2il/templates/base.html
wasa2il/templates/core/_election_list_table.html
wasa2il/templates/core/_polity_detail_elections.html
wasa2il/templates/core/polity_detail.html
wasa2il/templates/registration/login.html
wasa2il/templates/registration/password_reset_confirm.html

More UI fixes for election

---

gateway/icepirate.py

Argh, encoding bugs. Hate hate hate fix fix fix.

---

core/ajax/__init__.py
core/ajax/utils.py
core/authentication.py
core/static/js/wasa2il.js
wasa2il/templates/core/election_detail.html

Fix critical CSRF issue, fix crash in auth, UI fix when user is logged out

---

core/static/js/wasa2il.js
wasa2il/templates/core/election_detail.html

... what it says on the tin, I hope!

Election UI: Prevent UI updates mid-drag, simplify timer logic

---

AUTHORS
core/elections.py
core/models.py
core/urls.py
gateway/icepirate.py
gateway/register.py
gateway/urls.py
requirements.txt
wasa2il/templates/help/is/authors.html
wasa2il/templates/registration/data_disclaimer.html
wasa2il/templates/registration/login.html
wasa2il/templates/registration/registration_form.html

WIP: Election recount tool, pre-verified registration flow

---

core/elections.py

See individual commit messages!

Election.py work: --below constraints, STV+schulze counting, minor tweaks

---

core/static/css/application.css

I did not test this on my local wasa2il setup, just quick and dirty implementation.

UI: Make statistic hover toolbox bigger

---

core/templatetags/wasa2il.py
core/urls.py
wasa2il/templates/_breadcrumbs.html
wasa2il/templates/base.html
wasa2il/templates/core/document_update.html
wasa2il/templates/core/election_detail.html
wasa2il/templates/core/election_form.html
wasa2il/templates/core/election_list.html
wasa2il/templates/core/issue_detail.html
wasa2il/templates/core/issues_new.html
wasa2il/templates/core/polity_detail.html
wasa2il/templates/core/polity_form.html
wasa2il/templates/core/polity_list.html
wasa2il/templates/core/topic_detail.html
wasa2il/templates/core/topic_form.html

Hey!
Here's my implementation of a crumtail to make it more obvious for the user where he is and what he's viewing.
Discussed on issue #93 
Simple to add to views or change. 
Pictures, thousand words and all that :)

#93 Breadcrumbs for easier navigation in polities

---

.travis.yml
core/ajax/issue.py
core/ajax/topic.py
core/models.py
core/static/css/application.css
core/static/js/wasa2il.js
core/templatetags/wasa2il.py
core/urls.py
core/views.py
forum/json.py
wasa2il/templates/_comments_section.html
wasa2il/templates/base.html
wasa2il/templates/core/issue_detail.html
wasa2il/templates/core/topic_detail.html
wasa2il/templates/forum/discussion_detail.html

- Consistent rendering of comments by polling API
- Adds profile pic thumbnail to all comments
- Refactoring discussion/comments rendering in wasa2il.js
- Comment style similar to fb comments using grid (needs testing in older browsers, if anyone cares about them)

Comments rendering

---

README.md

Moved the alternative setup portion to the wiki

Readme: move alt-setup portion to wiki

---

README.md

When doing minimal changes locally and running the `script` section of `.travis.yml` I get the following msg:
> ERROR - environment variable CODACY_PROJECT_TOKEN is not defined.

Change README.md - checking if it breaks Travis

---

README.md

See issue #212 
Trying to make this project even easier to setup in order to attract more developers to help out.

Update README - now recommending virtualenv as the default
